123 again

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,99 +1,101 @@
+# Setting java 1.8
 language: android
 jdk:
 - oraclejdk8
-env:
-  global:
-  - ANDROID_API=28
-  - EMULATOR_API=24
-  - ANDROID_BUILD_TOOLS=28.0.0
-android:
-  components:
-  - tools
-  - android-$EMULATOR_API
-  - platform-tools
-  - tools
-  - build-tools-$ANDROID_BUILD_TOOLS
-  - android-$ANDROID_API
-  - extra-android-support
-  - extra-android-m2repository
-  - extra-google-m2repository
-  - sys-img-armeabi-v7a-android-$EMULATOR_API
-  licenses:
-  - ".+"
-before_script:
-- echo "y" | android update sdk -a --no-ui --filter android-$EMULATOR_API
-- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$EMULATOR_API
-- android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # list all targets
-- echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
-- emulator -avd test -no-skin -no-window &
-- android-wait-for-emulator
-- adb shell input keyevent 82 &
-- adb wait-for-device get-serialno
-- cd ${TRAVIS_BUILD_DIR}
-- chmod +x gradlew
-- ./gradlew --version
-- ./gradlew clean
-script:
-- |
-  ./gradlew build assembleAndroidTest -PtestCoverageEnabled='true'
-  retval=$?
-  if [ $retval -ne 0 ]; then
-    echo "error on assembling, exit code: "$retval
-    exit $retval
-  fi
-# See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
-# Instead of this (which doesn't give any output during tests execution):
-# - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
-# run:
-- |
-  ./gradlew :app:installDebug :app:installDebugAndroidTest -PtestCoverageEnabled='true'
-  retval=$?
-  if [ $retval -ne 0 ]; then
-    echo "error on install, exit code: "$retval
-    exit $retval
-  fi
-#
-# The below line causes Process crash due to absence of video device
-#- adb shell am instrument -w -r -e debug false org.andstatus.app.tests/android.test.InstrumentationTestRunner
-#
-# Run only tests, marked with a special annotation:
-# See https://developer.android.com/reference/android/test/InstrumentationTestRunner.html
-# For testing one method only:
-# - adb shell am instrument -w -r -e debug false -e coverage true -e class org.andstatus.app.service.CommandExecutorStrategyTest#testSearch org.andstatus.app.tests/androidx.test.runner.AndroidJUnitRunner
-- |
-  adb shell am instrument -w -r -e executionMode travisTest -e coverage true org.andstatus.app.tests/androidx.test.runner.AndroidJUnitRunner |& tee build/adb-test.log
-  retval=$?
-  if [ $retval -ne 0 ]; then
-    echo "error in adb, exit code: "$retval
-    exit $retval
-  fi
-# adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
-# So we need to parse saved terminal log
-- |
-  cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack=" | grep -v "org.junit.AssumptionViolatedException"
-  if [ $? -eq 0 ]; then
-    echo "Test failure found"
-    exit 1
-  else
-    cat build/adb-test.log | grep "OK ("
-  fi
-# Copy coverage data from the emulator
-- |
-  adb shell "rm /sdcard/Download/coverage.ec"
-  adb shell "run-as org.andstatus.app cp /data/user/0/org.andstatus.app/files/coverage.ec /sdcard/Download"
-- cd app/build
-# copy to "build" folder, where it will be found by Sonar scanner
-- adb pull "/sdcard/Download/coverage.ec"
-- cd ../..
-notifications:
-  email: false
+
+sudo: required # disables container-based builds which have a maximum of 4GB of memory
+
+# caching as advised by travis
+before_cache:
+- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
+- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
+
 cache:
   directories:
-  - $HOME/.m2
   - $HOME/.gradle/caches/
   - $HOME/.gradle/wrapper/
   - $HOME/.android/build-cache
+
+env:
+  matrix:
+  #  - EMULATOR_API_LEVEL=23  ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-23
+  #  - EMULATOR_API_LEVEL=22  ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-22
+  #  - EMULATOR_API_LEVEL=21  ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-21
+  - EMULATOR_API_LEVEL=24  ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-24
+
+  global:
+  - ANDROID_API_LEVEL=28
+  - ANDROID_BUILD_TOOLS_VERSION=28.0.0
+  - ADB_INSTALL_TIMEOUT=40 # wait up to 20 minutes for adb to connect to emulator (2 minutes by default)
+  - ANDROID_ABI=armeabi-v7a
+
+android:
+  components:
+  # Base components
+  - build-tools-$ANDROID_BUILD_TOOLS_VERSION # get the build tools version to build the project
+
+  # used sdk versions
+  - android-$ANDROID_API_LEVEL # get the android sdk version to build the project
+  - android-$EMULATOR_API_LEVEL # get the android sdk version for the emulator
+
+  # Get the latest version of additional components
+  - extra-android-support
+  - extra-google-m2repository
+  - extra-android-m2repository
+  - extra-google-google_play_services
+
+  # Specify the needed emulator
+  - $ANDROID_EMULATOR_IMAGE
+
+licenses:
+- android-sdk-license-5be876d5
+- 'android-sdk-license-.+'
+- '.+'
+
+# Emulator Management: Create, Start and Wait
 before_install:
-- yes | sdkmanager "platforms;android-$ANDROID_API"
-after_success:
-- ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true
+- echo $ANDROID_TARGET
+- echo $ANDROID_ABI
+- adb logcat > logcat.log &
+
+install:
+- sdkmanager --list || true # List all available targets, device definitions and AVDs.
+# Update sdk tools to latest version and install/update components
+- echo yes | sdkmanager "tools"
+- echo yes | sdkmanager "platform-tools"
+- echo yes | sdkmanager "build-tools;"$ANDROID_BUILD_TOOLS_VERSION
+- echo yes | sdkmanager "platforms;android-"$ANDROID_API_LEVEL # Latest platform required by SDK tools
+
+- echo yes | sdkmanager "extras;android;m2repository"
+- echo yes | sdkmanager "extras;google;m2repository"
+- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
+- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
+
+- echo yes | sdkmanager --update
+- echo yes | sdkmanager --licenses
+
+# Check components status
+- sdkmanager --list || true
+
+before_script:
+- chmod +x gradlew
+# Create and start the emulator
+- sdkmanager "system-images;android-"$EMULATOR_API_LEVEL";google_apis;armeabi-v7a"
+- echo no | avdmanager -v create avd -f -n test -k "system-images;android-"$EMULATOR_API_LEVEL";google_apis;armeabi-v7a"
+- $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
+
+- sleep 300
+
+# Turn off animations
+#- adb shell settings put global window_animation_scale 0 &
+#- adb shell settings put global transition_animation_scale 0 &
+#- adb shell settings put global animator_duration_scale 0 &
+
+# Wake up
+- adb shell input keyevent 82 &
+script:
+- ./gradlew test #--debug # Local unit test
+- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
+after_script:
+- echo $ANDROID_TARGET
+- echo $ANDROID_ABI
